// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace MLDotNet_Server
{
    public partial class MLModel
    {
        /// <summary>
        /// model input class for MLModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(5)]
            [ColumnName(@"Product Purchased")]
            public string Product_Purchased { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"Date of Purchase")]
            public string Date_of_Purchase { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"Ticket Type")]
            public string Ticket_Type { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"Ticket Subject")]
            public string Ticket_Subject { get; set; }

            [LoadColumn(9)]
            [ColumnName(@"Ticket Description")]
            public string Ticket_Description { get; set; }

            [LoadColumn(10)]
            [ColumnName(@"Ticket Status")]
            public string Ticket_Status { get; set; }

            [LoadColumn(12)]
            [ColumnName(@"Ticket Priority")]
            public string Ticket_Priority { get; set; }

            [LoadColumn(13)]
            [ColumnName(@"Ticket Channel")]
            public string Ticket_Channel { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Product Purchased")]
            public float[] Product_Purchased { get; set; }

            [ColumnName(@"Date of Purchase")]
            public float[] Date_of_Purchase { get; set; }

            [ColumnName(@"Ticket Type")]
            public float[] Ticket_Type { get; set; }

            [ColumnName(@"Ticket Subject")]
            public float[] Ticket_Subject { get; set; }

            [ColumnName(@"Ticket Description")]
            public float[] Ticket_Description { get; set; }

            [ColumnName(@"Ticket Status")]
            public float[] Ticket_Status { get; set; }

            [ColumnName(@"Ticket Priority")]
            public uint Ticket_Priority { get; set; }

            [ColumnName(@"Ticket Channel")]
            public float[] Ticket_Channel { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public string PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLModel.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict scores for all possible labels.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static IOrderedEnumerable<KeyValuePair<string, float>> PredictAllLabels(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            var result = predEngine.Predict(input);
            return GetSortedScoresWithLabels(result);
        }

        /// <summary>
        /// Map the unlabeled result score array to the predicted label names.
        /// </summary>
        /// <param name="result">Prediction to get the labeled scores from.</param>
        /// <returns>Ordered list of label and score.</returns>
        /// <exception cref="Exception"></exception>
        public static IOrderedEnumerable<KeyValuePair<string, float>> GetSortedScoresWithLabels(ModelOutput result)
        {
            var unlabeledScores = result.Score;
            var labelNames = GetLabels(result);

            Dictionary<string, float> labledScores = new Dictionary<string, float>();
            for (int i = 0; i < labelNames.Count(); i++)
            {
                // Map the names to the predicted result score array
                var labelName = labelNames.ElementAt(i);
                labledScores.Add(labelName.ToString(), unlabeledScores[i]);
            }

            return labledScores.OrderByDescending(c => c.Value);
        }

        /// <summary>
        /// Get the ordered label names.
        /// </summary>
        /// <param name="result">Predicted result to get the labels from.</param>
        /// <returns>List of labels.</returns>
        /// <exception cref="Exception"></exception>
        private static IEnumerable<string> GetLabels(ModelOutput result)
        {
            var schema = PredictEngine.Value.OutputSchema;

            var labelColumn = schema.GetColumnOrNull("Ticket Priority");
            if (labelColumn == null)
            {
                throw new Exception("Ticket Priority column not found. Make sure the name searched for matches the name in the schema.");
            }

            // Key values contains an ordered array of the possible labels. This allows us to map the results to the correct label value.
            var keyNames = new VBuffer<ReadOnlyMemory<char>>();
            labelColumn.Value.GetKeyValues(ref keyNames);
            return keyNames.DenseValues().Select(x => x.ToString());
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
